<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Core\Core.Facade\Core.Facade.csproj" />
    <ProjectReference Include="..\Modules\Users\Users.Facade\Users.Facade.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Users.ArchitectureTests" />
  </ItemGroup>

</Project>
